#!/bin/sh
# Generate a new ssh key if not exists
if [ "$1" == "force" ]; then
    rm -f /data/ssh/*
    rm -f ~/.ssh/*
    rm -f /root/.ssh/*
fi
if [ ! -f /data/ssh/id_ed25519 ]; then
   echo "[+] ]Generating a new ssh key..."
   ssh-keygen -t ed25519 -f /data/ssh/id_ed25519 -q -N ""
   echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > /data/ssh/config
   echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> /data/ssh/config
   chmod 600 /data/ssh/config
   chmod 700 /data/ssh
else 
   echo "[-] SSH key already exists."
fi
if [ ! -f ~/.ssh/id_ed25519 ]; then
   ME=$(whoami)
   echo "[+] Installing ssh key to $ME user..."
   cp -Rf /data/ssh ~/.ssh
   chown $ME:$ME -R ~/.ssh
fi
if [ "$1" == "copy" ]; then
   echo "[+] Replacing root's ssh key..."
   cp -Rf /data/ssh /root/.ssh
   chown root:root -R /root/.ssh
fi 